# Generated by Django 4.0 on 2022-08-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_alter_github_followers_alter_github_following_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Github',
            new_name='Repository',
        ),
    ]
